name: CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        browser: [
          'chrome'
        ]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn install
    - name: ESLint
      run: yarn lint:js
    - name: 'TemplateLint'
      run: yarn lint:hbs
    - name: Integration Tests
      env:
        CI: true
      run: yarn test:ember --host 127.0.0.1 --launch ${{ matrix.browser }}
  build-macos:
    runs-on: macos-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        browser: [
          'safari'
        ]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn install
    - name: ESLint
      run: yarn lint:js
    - name: 'TemplateLint'
      run: yarn lint:hbs
    - name: Integration Tests
      env:
        CI: true
      run: yarn test:ember --host 127.0.0.1 --launch ${{ matrix.browser }}
